export const LOGIN_LOADING ="LOGIN_LOADING";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_ERROR ="LOGIN_ERROR";
export const LOGIN_RELOADING ="LOGIN_RELOADING";

export const REGISTER_LOADING ="REGISTER_LOADING";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_ERROR ="REGISTER_ERROR";
export const REGISTER_RELOADING ="REGISTER_RELOADING";

export const RESET_STATE_FAIL =  "RESET_STATE_FAIL";
export const RESET_STATE_LOADING =  "RESET_STATE_LOADING";
export const RESET_STATE_RELOAD =  "RESET_STATE_RELOAD";
export const RESET_STATE_SUCCEED = "RESET_STATE_SUCCEED";

export const CATEGORY_FAIL =  "CATEGORY_FAIL";
export const CATEGORY_LOADING =  "CATEGORY_LOADING";
export const CATEGORY_RELOAD =  "CATEGORY_RELOAD";
export const CATEGORY_SUCCEED = "CATEGORY_SUCCEED";

export const FARM_FAIL =  "FARM_FAIL";
export const FARM_LOADING =  "FARM_LOADING";
export const FARM_RELOAD =  "FARM_RELOAD";
export const FARM_SUCCEED = "FARM_SUCCEED";

export const SUBMIT_REQUEST_FAIL =  "SUBMIT_REQUEST_FAIL";
export const SUBMIT_REQUEST_LOADING =  "SUBMIT_REQUEST_LOADING";
export const SUBMIT_REQUEST_RELOAD =  "SUBMIT_REQUEST_RELOAD";
export const SUBMIT_REQUEST_SUCCEED = "SUBMIT_REQUEST_SUCCEED";

export const ADD_FARM_FAIL =  "ADD_FARM_FAIL";
export const ADD_FARM_LOADING =  "ADD_FARM_LOADING";
export const ADD_FARM_RELOAD =  "ADD_FARM_RELOAD";
export const ADD_FARM_SUCCEED = "ADD_FARM_SUCCEED";

export const DELETE_FARM_FAIL =  "DELETE_FARM_FAIL";
export const DELETE_FARM_LOADING =  "DELETE_FARM_LOADING";
export const DELETE_FARM_RELOAD =  "DELETE_FARM_RELOAD";
export const DELETE_FARM_SUCCEED = "DELETE_FARM_SUCCEED";

export const ALL_FARM_FAIL =  "ALL_FARM_FAIL";
export const ALL_FARM_LOADING =  "ALL_FARM_LOADING";
export const ALL_FARM_RELOAD =  "ALL_FARM_RELOAD";
export const ALL_FARM_SUCCEED = "ALL_FARM_SUCCEED";

export const GET_FARM_FAIL =  "GET_FARM_FAIL";
export const GET_FARM_LOADING =  "GET_FARM_LOADING";
export const GET_FARM_RELOAD =  "GET_FARM_RELOAD";
export const GET_FARM_SUCCEED = "GET_FARM_SUCCEED";

export const EDIT_FARM_FAIL =  "EDIT_FARM_FAIL";
export const EDIT_FARM_LOADING =  "EDIT_FARM_LOADING";
export const EDIT_FARM_RELOAD =  "EDIT_FARM_RELOAD";
export const EDIT_FARM_SUCCEED = "EDIT_FARM_SUCCEED";

export const FORGET_PASSWORD_FAIL =  "FORGET_PASSWORD_FAIL";
export const FORGET_PASSWORD_LOADING =  "FORGET_PASSWORD_LOADING";
export const FORGET_PASSWORD_RELOAD =  "FORGET_PASSWORD_RELOAD";
export const FORGET_PASSWORD_SUCCEED = "FORGET_PASSWORD_SUCCEED";

export const VERIFY_OTP_FAIL =  "VERIFY_OTP_FAIL";
export const VERIFY_OTP_LOADING =  "VERIFY_OTP_LOADING";
export const VERIFY_OTP_RELOAD =  "VERIFY_OTP_RELOAD";
export const VERIFY_OTP_SUCCEED = "VERIFY_OTP_SUCCEED";

export const RESET_PASSWORD_FAIL =  "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_LOADING =  "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_RELOAD =  "RESET_PASSWORD_RELOAD";
export const RESET_PASSWORD_SUCCEED = "RESET_PASSWORD_SUCCEED";

export const MY_PROFILE_FAIL =  "MY_PROFILE_FAIL";
export const MY_PROFILE_LOADING =  "MY_PROFILE_LOADING";
export const MY_PROFILE_RELOAD =  "MY_PROFILE_RELOAD";
export const MY_PROFILE_SUCCEED = "MY_PROFILE_SUCCEED";

export const UPDATE_PROFILE_FAIL =  "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_LOADING =  "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_RELOAD =  "UPDATE_PROFILE_RELOAD";
export const UPDATE_PROFILE_SUCCEED = "UPDATE_PROFILE_SUCCEED";

export const CURRENT_REQUEST_FAIL =  "CURRENT_REQUEST_FAIL";
export const CURRENT_REQUEST_LOADING =  "CURRENT_REQUEST_LOADING";
export const CURRENT_REQUEST_RELOAD =  "CURRENT_REQUEST_RELOAD";
export const CURRENT_REQUEST_SUCCEED = "CURRENT_REQUEST_SUCCEED";

export const PAST_REQUEST_FAIL =  "PAST_REQUEST_FAIL";
export const PAST_REQUEST_LOADING =  "PAST_REQUEST_LOADING";
export const PAST_REQUEST_RELOAD =  "PAST_REQUEST_RELOAD";
export const PAST_REQUEST_SUCCEED = "PAST_REQUEST_SUCCEED";

export const AUTH_FAIL =  "AUTH_FAIL";
export const AUTH_LOADING =  "AUTH_LOADING";
export const AUTH_RELOAD =  "AUTH_RELOAD";
export const AUTH_SUCCEED = "AUTH_SUCCEED";

export const CONSULTANT_SERVICE_REQUEST_FAIL =  "CONSULTANT_SERVICE_REQUEST_FAIL";
export const CONSULTANT_SERVICE_REQUEST_LOADING =  "CONSULTANT_SERVICE_REQUEST_LOADING";
export const CONSULTANT_SERVICE_REQUEST_RELOAD =  "CONSULTANT_SERVICE_REQUEST_RELOAD";
export const CONSULTANT_SERVICE_REQUEST_SUCCEED = "CONSULTANT_SERVICE_REQUEST_SUCCEED";

export const CONSULTANT_SERVICE_REQUEST_DETAIL_FAIL =  "CONSULTANT_SERVICE_REQUEST_DETAIL_FAIL";
export const CONSULTANT_SERVICE_REQUEST_DETAIL_LOADING =  "CONSULTANT_SERVICE_REQUEST_DETAIL_LOADING";
export const CONSULTANT_SERVICE_REQUEST_DETAIL_RELOAD =  "CONSULTANT_SERVICE_REQUEST_DETAIL_RELOAD";
export const CONSULTANT_SERVICE_REQUEST_DETAIL_SUCCEED = "CONSULTANT_SERVICE_REQUEST_DETAIL_SUCCEED";

export const PLANNING_FAIL =  "PLANNING_FAIL";
export const PLANNING_LOADING =  "PLANNING_LOADING";
export const PLANNING_RELOAD =  "PLANNING_RELOAD";
export const PLANNING_SUCCEED = "PLANNING_SUCCEED";

export const TASK_LIST_FAIL =  "TASK_LIST_FAIL";
export const TASK_LIST_LOADING =  "TASK_LIST_LOADING";
export const TASK_LIST_RELOAD =  "TASK_LIST_RELOAD";
export const TASK_LIST_SUCCEED = "TASK_LIST_SUCCEED";

export const TASK_LIST_DETAIL_FAIL =  "TASK_LIST_DETAIL_FAIL";
export const TASK_LIST_DETAIL_LOADING =  "TASK_LIST_DETAIL_LOADING";
export const TASK_LIST_DETAIL_RELOAD =  "TASK_LIST_DETAIL_RELOAD";
export const TASK_LIST_DETAIL_SUCCEED = "TASK_LIST_DETAIL_SUCCEED";

export const CONSULTANT_CURRENT_REQUEST_FAIL =  "CONSULTANT_CURRENT_REQUEST_FAIL";
export const CONSULTANT_CURRENT_REQUEST_LOADING =  "CONSULTANT_CURRENT_REQUEST_LOADING";
export const CONSULTANT_CURRENT_REQUEST_RELOAD =  "CONSULTANT_CURRENT_REQUEST_RELOAD";
export const CONSULTANT_CURRENT_REQUEST_SUCCEED = "CONSULTANT_CURRENT_REQUEST_SUCCEED";

export const CONSULTANT_PAST_REQUEST_FAIL =  "CONSULTANT_PAST_REQUEST_FAIL";
export const CONSULTANT_PAST_REQUEST_LOADING =  "CONSULTANT_PAST_REQUEST_LOADING";
export const CONSULTANT_PAST_REQUEST_RELOAD =  "CONSULTANT_PAST_REQUEST_RELOAD";
export const CONSULTANT_PAST_REQUEST_SUCCEED = "CONSULTANT_PAST_REQUEST_SUCCEED";

export const CONSULTANT_ADD_COMMENT_FAIL =  "CONSULTANT_ADD_COMMENT_FAIL";
export const CONSULTANT_ADD_COMMENT_LOADING =  "CONSULTANT_ADD_COMMENT_LOADING";
export const CONSULTANT_ADD_COMMENT_RELOAD =  "CONSULTANT_ADD_COMMENT_RELOAD";
export const CONSULTANT_ADD_COMMENT_SUCCEED = "CONSULTANT_ADD_COMMENT_SUCCEED";

export const QUESTIONS_FAIL =  "QUESTIONS_FAIL";
export const QUESTIONS_LOADING =  "QUESTIONS_LOADING";
export const QUESTIONS_RELOAD =  "QUESTIONS_RELOAD";
export const QUESTIONS_SUCCEED = "QUESTIONS_SUCCEED";

export const ALL_CONSULTANT_FAIL =  "ALL_CONSULTANT_FAIL";
export const ALL_CONSULTANT_LOADING =  "ALL_CONSULTANT_LOADING";
export const ALL_CONSULTANT_RELOAD =  "ALL_CONSULTANT_RELOAD";
export const ALL_CONSULTANT_SUCCEED = "ALL_CONSULTANT_SUCCEED";

export const UNASSIGNED_SERVICES_FAIL =  "UNASSIGNED_SERVICES_FAIL";
export const UNASSIGNED_SERVICES_LOADING =  "UNASSIGNED_SERVICES_LOADING";
export const UNASSIGNED_SERVICES_RELOAD =  "UNASSIGNED_SERVICES_RELOAD";
export const UNASSIGNED_SERVICES_SUCCEED = "UNASSIGNED_SERVICES_SUCCEED";

export const ASSIGNED_SERVICES_FAIL =  "ASSIGNED_SERVICES_FAIL";
export const ASSIGNED_SERVICES_LOADING =  "ASSIGNED_SERVICES_LOADING";
export const ASSIGNED_SERVICES_RELOAD =  "ASSIGNED_SERVICES_RELOAD";
export const ASSIGNED_SERVICES_SUCCEED = "ASSIGNED_SERVICES_SUCCEED";

export const ASSIGN_A_CONSULTANT_FAIL =  "ASSIGN_A_CONSULTANT_FAIL";
export const ASSIGN_A_CONSULTANT_LOADING =  "ASSIGN_A_CONSULTANT_LOADING";
export const ASSIGN_A_CONSULTANT_RELOAD =  "ASSIGN_A_CONSULTANT_RELOAD";
export const ASSIGN_A_CONSULTANT_SUCCEED = "ASSIGN_A_CONSULTANT_SUCCEED";

export const E_SERVICE_DETAILS_FAIL =  "E_SERVICE_DETAILS_FAIL";
export const E_SERVICE_DETAILS_LOADING =  "E_SERVICE_DETAILS_LOADING";
export const E_SERVICE_DETAILS_RELOAD =  "E_SERVICE_DETAILS_RELOAD";
export const E_SERVICE_DETAILS_SUCCEED = "E_SERVICE_DETAILS_SUCCEED";

export const E_TASKLIST_FAIL =  "E_TASKLIST_FAIL";
export const E_TASKLIST_LOADING =  "E_TASKLIST_LOADING";
export const E_TASKLIST_RELOAD =  "E_TASKLIST_RELOAD";
export const E_TASKLIST_SUCCEED = "E_TASKLIST_SUCCEED";

export const E_TASKDETAIL_FAIL =  "E_TASKDETAIL_FAIL";
export const E_TASKDETAIL_LOADING =  "E_TASKDETAIL_LOADING";
export const E_TASKDETAIL_RELOAD =  "E_TASKDETAIL_RELOAD";
export const E_TASKDETAIL_SUCCEED = "E_TASKDETAIL_SUCCEED";

export const E_CURRENT_REQUEST_FAIL =  "E_CURRENT_REQUEST_FAIL";
export const E_CURRENT_REQUEST_LOADING =  "E_CURRENT_REQUEST_LOADING";
export const E_CURRENT_REQUEST_RELOAD =  "E_CURRENT_REQUEST_RELOAD";
export const E_CURRENT_REQUEST_SUCCEED = "E_CURRENT_REQUEST_SUCCEED";

export const E_PAST_REQUEST_FAIL =  "E_PAST_REQUEST_FAIL";
export const E_PAST_REQUEST_LOADING =  "E_PAST_REQUEST_LOADING";
export const E_PAST_REQUEST_RELOAD =  "E_PAST_REQUEST_RELOAD";
export const E_PAST_REQUEST_SUCCEED = "E_PAST_REQUEST_SUCCEED";

export const ACCEPT_TASK_FAIL =  "ACCEPT_TASK_FAIL";
export const ACCEPT_TASK_LOADING =  "ACCEPT_TASK_LOADING";
export const ACCEPT_TASK_RELOAD =  "ACCEPT_TASK_RELOAD";
export const ACCEPT_TASK_SUCCEED = "ACCEPT_TASK_SUCCEED";

export const REJECT_TASK_FAIL =  "REJECT_TASK_FAIL";
export const REJECT_TASK_LOADING =  "REJECT_TASK_LOADING";
export const REJECT_TASK_RELOAD =  "REJECT_TASK_RELOAD";
export const REJECT_TASK_SUCCEED = "REJECT_TASK_SUCCEED";

export const ACCEPT_SERVICE_REQUEST_FAIL =  "ACCEPT_SERVICE_REQUEST_FAIL";
export const ACCEPT_SERVICE_REQUEST_LOADING =  "ACCEPT_SERVICE_REQUEST_LOADING";
export const ACCEPT_SERVICE_REQUEST_RELOAD =  "ACCEPT_SERVICE_REQUEST_RELOAD";
export const ACCEPT_SERVICE_REQUEST_SUCCEED = "ACCEPT_SERVICE_REQUEST_SUCCEED";

export const QUESTION_RESPONSE_FAIL =  "QUESTION_RESPONSE_FAIL";
export const QUESTION_RESPONSE_LOADING =  "QUESTION_RESPONSE_LOADING";
export const QUESTION_RESPONSE_RELOAD =  "QUESTION_RESPONSE_RELOAD";
export const QUESTION_RESPONSE_SUCCEED = "QUESTION_RESPONSE_SUCCEED";

export const VIEW_QUESTION_RESPONSE_FAIL =  "VIEW_QUESTION_RESPONSE_FAIL";
export const VIEW_QUESTION_RESPONSE_LOADING =  "VIEW_QUESTION_RESPONSE_LOADING";
export const VIEW_QUESTION_RESPONSE_RELOAD =  "VIEW_QUESTION_RESPONSE_RELOAD";
export const VIEW_QUESTION_RESPONSE_SUCCEED = "VIEW_QUESTION_RESPONSE_SUCCEED";

export const EXPORT_CSV_FAIL =  "EXPORT_CSV_FAIL";
export const EXPORT_CSV_LOADING =  "EXPORT_CSV_LOADING";
export const EXPORT_CSV_RELOAD =  "EXPORT_CSV_RELOAD";
export const EXPORT_CSV_SUCCEED = "EXPORT_CSV_SUCCEED";

export const SERVICE_DETAIL_FAIL =  "SERVICE_DETAIL_FAIL";
export const SERVICE_DETAIL_LOADING =  "SERVICE_DETAIL_LOADING";
export const SERVICE_DETAIL_RELOAD =  "SERVICE_DETAIL_RELOAD";
export const SERVICE_DETAIL_SUCCEED = "SERVICE_DETAIL_SUCCEED";

export const CANCEL_BOOKING_FAIL =  "CANCEL_BOOKING_FAIL";
export const CANCEL_BOOKING_LOADING =  "CANCEL_BOOKING_LOADING";
export const CANCEL_BOOKING_RELOAD =  "CANCEL_BOOKING_RELOAD";
export const CANCEL_BOOKING_SUCCEED = "CANCEL_BOOKING_SUCCEED";

export const UPDATE_PROFILE_PASSWORD_FAIL =  "UPDATE_PROFILE_PASSWORD_FAIL";
export const UPDATE_PROFILE_PASSWORD_LOADING =  "UPDATE_PROFILE_PASSWORD_LOADING";
export const UPDATE_PROFILE_PASSWORD_RELOAD =  "UPDATE_PROFILE_PASSWORD_RELOAD";
export const UPDATE_PROFILE_PASSWORD_SUCCEED = "UPDATE_PROFILE_PASSWORD_SUCCEED";

export const CLOSE_REQUEST_FAIL =  "CLOSE_REQUEST_FAIL";
export const CLOSE_REQUEST_LOADING =  "CLOSE_REQUEST_LOADING";
export const CLOSE_REQUEST_RELOAD =  "CLOSE_REQUEST_RELOAD";
export const CLOSE_REQUEST_SUCCEED = "CLOSE_REQUEST_SUCCEED";

export const LOCATEME_FAIL =  "LOCATEME_FAIL";
export const LOCATEME_LOADING =  "LOCATEME_LOADING";
export const LOCATEME_RELOAD =  "LOCATEME_RELOAD";
export const LOCATEME_SUCCEED = "LOCATEME_SUCCEED";

export const FAQ_FAIL =  "FAQ_FAIL";
export const FAQ_LOADING =  "FAQ_LOADING";
export const FAQ_RELOAD =  "FAQ_RELOAD";
export const FAQ_SUCCEED = "FAQ_SUCCEED";

export const ACTIVITY_STATUS_FAIL =  "ACTIVITY_STATUS_FAIL";
export const ACTIVITY_STATUS_LOADING =  "ACTIVITY_STATUS_LOADING";
export const ACTIVITY_STATUS_RELOAD =  "ACTIVITY_STATUS_RELOAD";
export const ACTIVITY_STATUS_SUCCEED = "ACTIVITY_STATUS_SUCCEED";

export const NOTIFICATION_FARMER_FAIL =  "NOTIFICATION_FARMER_FAIL";
export const NOTIFICATION_FARMER_LOADING =  "NOTIFICATION_FARMER_LOADING";
export const NOTIFICATION_FARMER_RELOAD =  "NOTIFICATION_FARMER_RELOAD";
export const NOTIFICATION_FARMER_SUCCEED = "NOTIFICATION_FARMER_SUCCEED";

export const TASK_EDIT_FAIL =  "TASK_EDIT_FAIL";
export const TASK_EDIT_LOADING =  "TASK_EDIT_LOADING";
export const TASK_EDIT_RELOAD =  "TASK_EDIT_RELOAD";
export const TASK_EDIT_SUCCEED = "TASK_EDIT_SUCCEED";

export const TASK_UPDATE_FAIL =  "TASK_UPDATE_FAIL";
export const TASK_UPDATE_LOADING =  "TASK_UPDATE_LOADING";
export const TASK_UPDATE_RELOAD =  "TASK_UPDATE_RELOAD";
export const TASK_UPDATE_SUCCEED = "TASK_UPDATE_SUCCEED";

export const COMPLETE_TASK_FAIL =  "COMPLETE_TASK_FAIL";
export const COMPLETE_TASK_LOADING =  "COMPLETE_TASK_LOADING";
export const COMPLETE_TASK_RELOAD =  "COMPLETE_TASK_RELOAD";
export const COMPLETE_TASK_SUCCEED = "COMPLETE_TASK_SUCCEED";