export const LOGIN_LOADING ="LOGIN_LOADING";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_ERROR ="LOGIN_ERROR";
export const LOGIN_RELOADING ="LOGIN_RELOADING";

export const REGISTER_LOADING ="REGISTER_LOADING";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_ERROR ="REGISTER_ERROR";
export const REGISTER_RELOADING ="REGISTER_RELOADING";

export const GET_POST_FAIL =  "GET_POST_FAIL";
export const GET_POST_LOADING =  "GET_POST_LOADING";
export const GET_POST_RELOAD =  "GET_POST_RELOAD";
export const GET_POST_SUCCEED = "GET_POST_SUCCEED";

export const AUTH_FAIL =  "AUTH_FAIL";
export const AUTH_LOADING =  "AUTH_LOADING";
export const AUTH_RELOAD =  "AUTH_RELOAD";
export const AUTH_SUCCEED = "AUTH_SUCCEED";
